### ISSUE TITLE
/SigmoidFocalLoss_cuda.cu error

### ISSUE THREAD

**Issue by iridescentZ** [MVIG-SJTU/AlphAction#42] opened 2020-12-14 14:36 UTC
when I run pip install -e . , there is something error. How to solve it ?

/home/action_detection/AlphAction/alphaction/csrc/cuda/SigmoidFocalLoss_cuda.cu(132): error: a pointer to a bound function may only be used to call the function

/home/action_detection/AlphAction/alphaction/csrc/cuda/SigmoidFocalLoss_cuda.cu(132): error: type name is not allowed

/home/action_detection/AlphAction/alphaction/csrc/cuda/SigmoidFocalLoss_cuda.cu(132): error: expected an expression

/home/action_detection/AlphAction/alphaction/csrc/cuda/SigmoidFocalLoss_cuda.cu(132): error: a pointer to a bound function may only be used to call the function

/home/action_detection/AlphAction/alphaction/csrc/cuda/SigmoidFocalLoss_cuda.cu(132): error: type name is not allowed

/home/action_detection/AlphAction/alphaction/csrc/cuda/SigmoidFocalLoss_cuda.cu(132): error: expected an expression

/home/action_detection/AlphAction/alphaction/csrc/cuda/SigmoidFocalLoss_cuda.cu(132): error: a pointer to a bound function may only be used to call the function

/home/action_detection/AlphAction/alphaction/csrc/cuda/SigmoidFocalLoss_cuda.cu(132): error: type name is not allowed

/home/action_detection/AlphAction/alphaction/csrc/cuda/SigmoidFocalLoss_cuda.cu(132): error: expected an expression

/home/action_detection/AlphAction/alphaction/csrc/cuda/SigmoidFocalLoss_cuda.cu(132): error: a pointer to a bound function may only be used to call the function

/home/action_detection/AlphAction/alphaction/csrc/cuda/SigmoidFocalLoss_cuda.cu(132): error: type name is not allowed

/home/action_detection/AlphAction/alphaction/csrc/cuda/SigmoidFocalLoss_cuda.cu(132): error: expected an expression

/home/action_detection/AlphAction/alphaction/csrc/cuda/SigmoidFocalLoss_cuda.cu(132): error: a pointer to a bound function may only be used to call the function

/home/action_detection/AlphAction/alphaction/csrc/cuda/SigmoidFocalLoss_cuda.cu(132): error: type name is not allowed

/home/action_detection/AlphAction/alphaction/csrc/cuda/SigmoidFocalLoss_cuda.cu(132): error: expected an expression

/home/action_detection/AlphAction/alphaction/csrc/cuda/SigmoidFocalLoss_cuda.cu(132): error: a pointer to a bound function may only be used to call the function

/home/action_detection/AlphAction/alphaction/csrc/cuda/SigmoidFocalLoss_cuda.cu(132): error: type name is not allowed

/home/action_detection/AlphAction/alphaction/csrc/cuda/SigmoidFocalLoss_cuda.cu(132): error: expected an expression

/home/action_detection/AlphAction/alphaction/csrc/cuda/SigmoidFocalLoss_cuda.cu(178): error: a pointer to a bound function may only be used to call the function

/home/action_detection/AlphAction/alphaction/csrc/cuda/SigmoidFocalLoss_cuda.cu(178): error: type name is not allowed

/home/action_detection/AlphAction/alphaction/csrc/cuda/SigmoidFocalLoss_cuda.cu(178): error: expected an expression

/home/action_detection/AlphAction/alphaction/csrc/cuda/SigmoidFocalLoss_cuda.cu(178): error: a pointer to a bound function may only be used to call the function

/home/action_detection/AlphAction/alphaction/csrc/cuda/SigmoidFocalLoss_cuda.cu(178): error: type name is not allowed

/home/action_detection/AlphAction/alphaction/csrc/cuda/SigmoidFocalLoss_cuda.cu(178): error: expected an expression

/home/action_detection/AlphAction/alphaction/csrc/cuda/SigmoidFocalLoss_cuda.cu(178): error: a pointer to a bound function may only be used to call the function

/home/action_detection/AlphAction/alphaction/csrc/cuda/SigmoidFocalLoss_cuda.cu(178): error: type name is not allowed

/home/action_detection/AlphAction/alphaction/csrc/cuda/SigmoidFocalLoss_cuda.cu(178): error: expected an expression

/home/action_detection/AlphAction/alphaction/csrc/cuda/SigmoidFocalLoss_cuda.cu(178): error: a pointer to a bound function may only be used to call the function

/home/action_detection/AlphAction/alphaction/csrc/cuda/SigmoidFocalLoss_cuda.cu(178): error: type name is not allowed

/home/action_detection/AlphAction/alphaction/csrc/cuda/SigmoidFocalLoss_cuda.cu(178): error: expected an expression

/home/action_detection/AlphAction/alphaction/csrc/cuda/SigmoidFocalLoss_cuda.cu(178): error: a pointer to a bound function may only be used to call the function

/home/action_detection/AlphAction/alphaction/csrc/cuda/SigmoidFocalLoss_cuda.cu(178): error: type name is not allowed

/home/action_detection/AlphAction/alphaction/csrc/cuda/SigmoidFocalLoss_cuda.cu(178): error: expected an expression

/home/action_detection/AlphAction/alphaction/csrc/cuda/SigmoidFocalLoss_cuda.cu(178): error: a pointer to a bound function may only be used to call the function

/home/action_detection/AlphAction/alphaction/csrc/cuda/SigmoidFocalLoss_cuda.cu(178): error: type name is not allowed

/home/action_detection/AlphAction/alphaction/csrc/cuda/SigmoidFocalLoss_cuda.cu(178): error: expected an expression

/home/action_detection/AlphAction/alphaction/csrc/cuda/SigmoidFocalLoss_cuda.cu(178): error: a pointer to a bound function may only be used to call the function

/home/action_detection/AlphAction/alphaction/csrc/cuda/SigmoidFocalLoss_cuda.cu(178): error: type name is not allowed

/home/action_detection/AlphAction/alphaction/csrc/cuda/SigmoidFocalLoss_cuda.cu(178): error: expected an expression

/home/action_detection/AlphAction/alphaction/csrc/cuda/SigmoidFocalLoss_cuda.cu(178): error: a pointer to a bound function may only be used to call the function

/home/action_detection/AlphAction/alphaction/csrc/cuda/SigmoidFocalLoss_cuda.cu(178): error: type name is not allowed

/home/action_detection/AlphAction/alphaction/csrc/cuda/SigmoidFocalLoss_cuda.cu(178): error: expected an expression

42 errors detected in the compilation of "/tmp/tmpxft_000017b7_00000000-6_SigmoidFocalLoss_cuda.cpp1.ii".
error: command '/usr/local/cuda/bin/nvcc' failed with exit status 1

**Comment by yelantf** [comment] 2020-12-14 15:36
This issue seems to be a duplicate of issue #28 . Please try the suggestions provided in the link https://github.com/MVIG-SJTU/AlphAction/issues/28#issuecomment-713266897.

**Comment by z1z9b89** [comment] 2020-12-16 03:04
Mybe I can give u some help , you can try  conda  create -n alphaction  python=3.8,   Don't use python3.7.

**Comment by iridescentZ** [comment] 2020-12-17 11:07
> This issue seems to be a duplicate of issue #28 . Please try the suggestions provided in the link [#28 (comment)](https://github.com/MVIG-SJTU/AlphAction/issues/28#issuecomment-713266897).

Thank you for quick reply! It helps, I updated the pytorch to version 1.3.0, the error disappeared. 
But there is a new error.  when I run demo.py using the pretrained model common_15cat_res101.pth, the computer shut down as it processed to the 33th frame. I try to find the reason,but can't figure out why it coused the computer to reboot. Looking forward for your reply!
the command  I used is as follow:
python demo.py --video-path Fighting033_x264.mp4  --output-path ./output.mp4 --cfg-path ~/ZSJ/action_detection/AlphAction/config_files/resnet101_8x8f_denseserial.yaml --weight-path ~/ZSJ/action_detection/AlphAction/data/models/aia_models/common_15cat_res101.pth --common-cate

**Comment by iridescentZ** [comment] 2020-12-17 11:09
> Mybe I can give u some help , you can try conda create -n alphaction python=3.8, Don't use python3.7.

Thank your for suggestion. The main problem is the version pytorch 1.0.0 is not match to the code. Updating the pytorch works~

**Comment by iridescentZ** [comment] 2020-12-19 07:21
> > This issue seems to be a duplicate of issue #28 . Please try the suggestions provided in the link [#28 (comment)](https://github.com/MVIG-SJTU/AlphAction/issues/28#issuecomment-713266897).
> 
> Thank you for quick reply! It helps, I updated the pytorch to version 1.3.0, the error disappeared.
> But there is a new error. when I run demo.py using the pretrained model common_15cat_res101.pth, the computer shut down as it processed to the 33th frame. I try to find the reason,but can't figure out why it coused the computer to reboot. Looking forward for your reply!
> the command I used is as follow:
> python demo.py --video-path Fighting033_x264.mp4 --output-path ./output.mp4 --cfg-path ~/ZSJ/action_detection/AlphAction/config_files/resnet101_8x8f_denseserial.yaml --weight-path ~/ZSJ/action_detection/AlphAction/data/models/aia_models/common_15cat_res101.pth --common-cate

Computer shutting down is due to  the power protection of GPU. I sovled this problem by set the limitation of GPU to 150w by using the command:
sudo nvidia-smi -pl 150

**Closed as completed** 2020-12-28 07:42 UTC
Labels: installation
