### ISSUE TITLE
Good Morrning  author! when I use webcam run a moment then  throw out an Error 

### ISSUE THREAD

**Issue by Seiano** [MVIG-SJTU/AlphAction#36] opened 2020-11-09 01:24 UTC
**(alphaction) zhangzhenbo@zhangzhenbo-TUF-Gaming-FX505GM-FX86FM:~/AlphAction/demo$  python demo.py  --webcam    --output-path ../output/Joe_Biden.avi   --cfg-path  ../config_files/resnet101_8x8f_denseserial.yaml  --weight-path ../data/models/aia_models/resnet101_8x8f_denseserial.pth
Starting webcam demo, press Ctrl + C to terminate...
Loading action model weight from ../data/models/aia_models/resnet101_8x8f_denseserial.pth.
Action model weight successfully loaded.
Loading YOLO model..
Network successfully loaded
Loading tracking model..
Network successfully loaded
Showing tracking progress bar (in fps). Other processes are running in the background.
Tracker Progress: 148 frame [00:27,  5.16 frame/s]Process Process-2:
Tracker Progress: 149 frame [00:27,  5.55 frame/s]Traceback (most recent call last):
  File "/home/zhangzhenbo/anaconda3/envs/alphaction/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/zhangzhenbo/anaconda3/envs/alphaction/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/zhangzhenbo/AlphAction/demo/action_predictor.py", line 427, in _compute_prediction
    transform_randoms)
  File "/home/zhangzhenbo/AlphAction/demo/action_predictor.py", line 118, in update_feature
    assert timestamp > self.mem_timestamps[-1], "features are expected to be updated in order."
AssertionError: features are expected to be updated in order.
Tracker Progress: 636 frame [01:35,  7.16 frame/s]**

This mean I can't  run a long  time used webcam?

**Comment by yelantf** [comment] 2020-11-09 11:53
Sorry, I can not reproduce this problem. Is this always happening or just on occasion?

**Comment by irvingzhang0512** [comment] 2020-11-10 09:27
me too, it happens all the time.

**Comment by irvingzhang0512** [comment] 2020-11-10 10:19
I tried several models. It seems that `--common-cat` model has this issue.

**Comment by yelantf** [comment] 2020-11-10 11:06
> I tried several models. It seems that `--common-cat` model has this issue.

I don't think it is related to specific models. Could you please try replacing the following line

https://github.com/MVIG-SJTU/AlphAction/blob/99acc16d4fd91ddd91d34665ee9c21607ebbd9a0/demo/action_predictor.py#L118

with `assert timestamp >= self.mem_timestamps[-1], "features are expected to be updated in order."` ?

**Comment by Seiano** [comment] 2020-11-10 11:24
I  have tried  but this error still  and  I don't know the  mean of this  line。

**Comment by yelantf** [comment] 2020-11-10 13:52
Could you please help to replace `demo/action_predictor.py` with this script [action_predictor.py](https://github.com/MVIG-SJTU/AlphAction/files/5517693/action_predictor.txt) (rename it to `action_predictor.py` manually) and then provide me with the log file `demo/debug.log`? Because only in that way I can locate where the problem is. Thank you in advance!

**Comment by pxssw** [comment] 2020-11-11 09:05
The code of  "assert timestamp > self.mem_timestamps[-1], "features are expected to be updated in order." " will make error sometimes, but by changing it ,as above, (> change to >=) or shielding this line can solve it , in my progect. 
But I find the error actually happened  in the part of demo/action_predictor.py/update_feature, I think mabe there is a bug in this function, you can change the line as above firstly, and then conform the error you meet whether happend in the "updata_feature"(you can show me the error info of your print log or adding a log info of this part manually, maybe we can solve it) @Seiano @irvingzhang0512

**Comment by irvingzhang0512** [comment] 2020-11-12 03:39
A few days ago, I did comment `assert timestamp > self.mem_timestamps[-1], "features are expected to be updated in order."` and run demo, but another error occured. Didn't save the error msg, but I remember that error is `device not available` or something(after that error, cannot read frame from `cap = cv2.VideoCapture(0)` )
Test machine is restored and I cannot reproduce the error right now. Maybe next week I can do some tests.
@yelantf @pxssw

**Comment by Seiano** [comment] 2020-11-19 07:57
### When I replace the code,The error still exists
`/home/tysk-zzb01/.conda/envs/alphaction/lib/python3.7/site-packages/torch/nn/modules/container.py:550: UserWarning: Setting attributes on ParameterDict is not supported.
  warnings.warn("Setting attributes on ParameterDict is not supported.")
Loading action model weight from ../data/models/aia_models/resnet101_8x8f_denseserial.pth.
Action model weight successfully loaded.
Loading YOLO model..
Network successfully loaded
Loading tracking model..
Network successfully loaded
Showing tracking progress bar (in fps). Other processes are running in the background.
Tracker Progress: 1930 frame [05:24,  5.64 frame/s]Process Process-4:
Traceback (most recent call last):
  File "/home/tysk-zzb01/.conda/envs/alphaction/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/tysk-zzb01/.conda/envs/alphaction/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/tysk-zzb01/AlphAction/demo/action_predictor.py", line 437, in _compute_prediction
    transform_randoms)
  File "/home/tysk-zzb01/AlphAction/demo/action_predictor.py", line 118, in update_feature
    assert timestamp > self.mem_timestamps[-1], "features are expected to be updated in order."
AssertionError: features are expected to be updated in order.
`

**Comment by Seiano** [comment] 2020-11-19 08:02
### When I replace that code,the Error still exists.


/home/tysk-zzb01/.conda/envs/alphaction/lib/python3.7/site-packages/torch/nn/modules/container.py:550: UserWarning: Setting attributes on ParameterDict is not supported.
  warnings.warn("Setting attributes on ParameterDict is not supported.")
Loading action model weight from ../data/models/aia_models/resnet101_8x8f_denseserial.pth.
Action model weight successfully loaded.
Loading YOLO model..
Network successfully loaded
Loading tracking model..
Network successfully loaded
Showing tracking progress bar (in fps). Other processes are running in the background.
Tracker Progress: 1930 frame [05:24,  5.64 frame/s]Process Process-4:
Traceback (most recent call last):
  File "/home/tysk-zzb01/.conda/envs/alphaction/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/tysk-zzb01/.conda/envs/alphaction/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/tysk-zzb01/AlphAction/demo/action_predictor.py", line 437, in _compute_prediction
    transform_randoms)
  File "/home/tysk-zzb01/AlphAction/demo/action_predictor.py", line 118, in update_feature
    assert timestamp > self.mem_timestamps[-1], "features are expected to be updated in order."
AssertionError: features are expected to be updated in order.
@pxssw @yelantf

**Comment by yelantf** [comment] 2020-11-19 08:06
> ### When I replace that code,the Error still exists.
> /home/tysk-zzb01/.conda/envs/alphaction/lib/python3.7/site-packages/torch/nn/modules/container.py:550: UserWarning: Setting attributes on ParameterDict is not supported.
> warnings.warn("Setting attributes on ParameterDict is not supported.")
> Loading action model weight from ../data/models/aia_models/resnet101_8x8f_denseserial.pth.
> Action model weight successfully loaded.
> Loading YOLO model..
> Network successfully loaded
> Loading tracking model..
> Network successfully loaded
> Showing tracking progress bar (in fps). Other processes are running in the background.
> Tracker Progress: 1930 frame [05:24, 5.64 frame/s]Process Process-4:
> Traceback (most recent call last):
> File "/home/tysk-zzb01/.conda/envs/alphaction/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
> self.run()
> File "/home/tysk-zzb01/.conda/envs/alphaction/lib/python3.7/multiprocessing/process.py", line 99, in run
> self._target(*self._args, **self._kwargs)
> File "/home/tysk-zzb01/AlphAction/demo/action_predictor.py", line 437, in _compute_prediction
> transform_randoms)
> File "/home/tysk-zzb01/AlphAction/demo/action_predictor.py", line 118, in update_feature
> assert timestamp > self.mem_timestamps[-1], "features are expected to be updated in order."
> AssertionError: features are expected to be updated in order.
> @pxssw @yelantf

According to your log, you did not replace the code successfully because in the log it is still ` timestamp > self.mem_timestamps[-1]` instead of ` timestamp >= self.mem_timestamps[-1]`.

**Comment by Seiano** [comment] 2020-11-19 09:16
Tracker Progress: 2315 frame [06:36,  5.84 frame/s]
Traceback (most recent call last):
  File "demo.py", line 194, in <module>
    main()
  File "demo.py", line 165, in main
    result = ava_predictor_worker.read()
  File "/home/tysk-zzb01/AlphAction/demo/action_predictor.py", line 327, in read
    return self.output_queue.get_nowait()
  File "/home/tysk-zzb01/.conda/envs/alphaction/lib/python3.7/multiprocessing/queues.py", line 126, in get_nowait
Traceback (most recent call last):
  File "/home/tysk-zzb01/.conda/envs/alphaction/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/tysk-zzb01/.conda/envs/alphaction/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/tysk-zzb01/AlphAction/demo/action_predictor.py", line 454, in _compute_prediction
    self.ava_predictor.clear_feature(feature_index)
  File "/home/tysk-zzb01/AlphAction/demo/action_predictor.py", line 183, in clear_feature
    del self.object_pool["SingleVideo", t]
  File "/home/tysk-zzb01/AlphAction/alphaction/structures/memory_pool.py", line 28, in __delitem__
    del self.cache[item[0]][item[1]]
KeyError: 369
    return self.get(False)
  File "/home/tysk-zzb01/.conda/envs/alphaction/lib/python3.7/multiprocessing/queues.py", line 113, in get
    return _ForkingPickler.loads(res)
  File "/home/tysk-zzb01/.conda/envs/alphaction/lib/python3.7/site-packages/torch/multiprocessing/reductions.py", line 282, in rebuild_storage_fd
    fd = df.detach()
  File "/home/tysk-zzb01/.conda/envs/alphaction/lib/python3.7/multiprocessing/resource_sharer.py", line 57, in detach
    with _resource_sharer.get_connection(self._id) as conn:
  File "/home/tysk-zzb01/.conda/envs/alphaction/lib/python3.7/multiprocessing/resource_sharer.py", line 87, in get_connection
    c = Client(address, authkey=process.current_process().authkey)
  File "/home/tysk-zzb01/.conda/envs/alphaction/lib/python3.7/multiprocessing/connection.py", line 492, in Client
    c = SocketClient(address)
  File "/home/tysk-zzb01/.conda/envs/alphaction/lib/python3.7/multiprocessing/connection.py", line 620, in SocketClient
    s.connect(address)
FileNotFoundError: [Errno 2] No such file or directory

**Comment by z1z9b89** [comment] 2020-11-19 09:30
Mybe my ideo is too long?  How long can this method handle video?   my video time is 5 minutes .

**Comment by z1z9b89** [comment] 2020-11-19 09:31
Mybe my video is too long? my video time is 5 minutes .
How long can this method handle video?

**Comment by yelantf** [comment] 2020-11-19 10:46
> Tracker Progress: 2315 frame [06:36, 5.84 frame/s]
> Traceback (most recent call last):
> File "demo.py", line 194, in
> main()
> File "demo.py", line 165, in main
> result = ava_predictor_worker.read()
> File "/home/tysk-zzb01/AlphAction/demo/action_predictor.py", line 327, in read
> return self.output_queue.get_nowait()
> File "/home/tysk-zzb01/.conda/envs/alphaction/lib/python3.7/multiprocessing/queues.py", line 126, in get_nowait
> Traceback (most recent call last):
> File "/home/tysk-zzb01/.conda/envs/alphaction/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
> self.run()
> File "/home/tysk-zzb01/.conda/envs/alphaction/lib/python3.7/multiprocessing/process.py", line 99, in run
> self._target(*self._args, **self._kwargs)
> File "/home/tysk-zzb01/AlphAction/demo/action_predictor.py", line 454, in _compute_prediction
> self.ava_predictor.clear_feature(feature_index)
> File "/home/tysk-zzb01/AlphAction/demo/action_predictor.py", line 183, in clear_feature
> del self.object_pool["SingleVideo", t]
> File "/home/tysk-zzb01/AlphAction/alphaction/structures/memory_pool.py", line 28, in **delitem**
> del self.cache[item[0]][item[1]]
> KeyError: 369
> return self.get(False)
> File "/home/tysk-zzb01/.conda/envs/alphaction/lib/python3.7/multiprocessing/queues.py", line 113, in get
> return _ForkingPickler.loads(res)
> File "/home/tysk-zzb01/.conda/envs/alphaction/lib/python3.7/site-packages/torch/multiprocessing/reductions.py", line 282, in rebuild_storage_fd
> fd = df.detach()
> File "/home/tysk-zzb01/.conda/envs/alphaction/lib/python3.7/multiprocessing/resource_sharer.py", line 57, in detach
> with _resource_sharer.get_connection(self._id) as conn:
> File "/home/tysk-zzb01/.conda/envs/alphaction/lib/python3.7/multiprocessing/resource_sharer.py", line 87, in get_connection
> c = Client(address, authkey=process.current_process().authkey)
> File "/home/tysk-zzb01/.conda/envs/alphaction/lib/python3.7/multiprocessing/connection.py", line 492, in Client
> c = SocketClient(address)
> File "/home/tysk-zzb01/.conda/envs/alphaction/lib/python3.7/multiprocessing/connection.py", line 620, in SocketClient
> s.connect(address)
> FileNotFoundError: [Errno 2] No such file or directory

 How did you get to this error? Could you please elaborate more?  @Seiano

**Comment by yelantf** [comment] 2020-11-19 10:48
> Mybe my video is too long? my video time is 5 minutes .
> How long can this method handle video?

Sorry, I don't understand your reply. What problem did you encounter? @z1z9b89

**Comment by pxssw** [comment] 2020-11-19 10:52
> Tracker Progress: 2315 frame [06:36, 5.84 frame/s]
> Traceback (most recent call last):
> File "demo.py", line 194, in
> main()
> File "demo.py", line 165, in main
> result = ava_predictor_worker.read()
> File "/home/tysk-zzb01/AlphAction/demo/action_predictor.py", line 327, in read
> return self.output_queue.get_nowait()
> File "/home/tysk-zzb01/.conda/envs/alphaction/lib/python3.7/multiprocessing/queues.py", line 126, in get_nowait
> Traceback (most recent call last):
> File "/home/tysk-zzb01/.conda/envs/alphaction/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
> self.run()
> File "/home/tysk-zzb01/.conda/envs/alphaction/lib/python3.7/multiprocessing/process.py", line 99, in run
> self._target(*self._args, **self._kwargs)
> File "/home/tysk-zzb01/AlphAction/demo/action_predictor.py", line 454, in _compute_prediction
> self.ava_predictor.clear_feature(feature_index)
> File "/home/tysk-zzb01/AlphAction/demo/action_predictor.py", line 183, in clear_feature
> del self.object_pool["SingleVideo", t]
> File "/home/tysk-zzb01/AlphAction/alphaction/structures/memory_pool.py", line 28, in **delitem**
> del self.cache[item[0]][item[1]]
> KeyError: 369
> return self.get(False)
> File "/home/tysk-zzb01/.conda/envs/alphaction/lib/python3.7/multiprocessing/queues.py", line 113, in get
> return _ForkingPickler.loads(res)
> File "/home/tysk-zzb01/.conda/envs/alphaction/lib/python3.7/site-packages/torch/multiprocessing/reductions.py", line 282, in rebuild_storage_fd
> fd = df.detach()
> File "/home/tysk-zzb01/.conda/envs/alphaction/lib/python3.7/multiprocessing/resource_sharer.py", line 57, in detach
> with _resource_sharer.get_connection(self._id) as conn:
> File "/home/tysk-zzb01/.conda/envs/alphaction/lib/python3.7/multiprocessing/resource_sharer.py", line 87, in get_connection
> c = Client(address, authkey=process.current_process().authkey)
> File "/home/tysk-zzb01/.conda/envs/alphaction/lib/python3.7/multiprocessing/connection.py", line 492, in Client
> c = SocketClient(address)
> File "/home/tysk-zzb01/.conda/envs/alphaction/lib/python3.7/multiprocessing/connection.py", line 620, in SocketClient
> s.connect(address)
> FileNotFoundError: [Errno 2] No such file or directory

There need a judgement before del, just like change the code 
"for t in self.mem_timestamps[:mem_to_release]:
            del self.mem_pool["SingleVideo", t]"
of the **clear_feature** part
 into:
"mem_timestamps_items = self.mem_pool["SingleVideo"]
        for t in self.mem_timestamps[:mem_to_release]:
            if t in mem_timestamps_items.keys():
                del self.mem_pool["SingleVideo", t]"

**Comment by Seiano** [comment] 2020-11-20 03:17
### This is my replay code:

        mem_timestamps_items = self.mem_pool["SingleVideo"]
        for t in self.mem_timestamps[:mem_to_release]:
            if t in mem_timestamps_items.keys():
                del self.mem_pool["SingleVideo", t]

### That's the Error  and I found a question  that  my video time is  5:12  but the Tracker Progress  frame's time is   06:32,  why?   

Tracker Progress: 2321 frame [06:32,  6.00 frame/s]Process Process-4:
Tracker Progress: 2321 frame [06:32,  5.91 frame/s]
Traceback (most recent call last):
  File "demo.py", line 194, in <module>
    main()
  File "demo.py", line 165, in main
    result = ava_predictor_worker.read()
  File "/home/tysk-zzb01/AlphAction/demo/action_predictor.py", line 336, in read
    return self.output_queue.get_nowait()
  File "/home/tysk-zzb01/.conda/envs/alphaction/lib/python3.7/multiprocessing/queues.py", line 126, in get_nowait
    return self.get(False)
  File "/home/tysk-zzb01/.conda/envs/alphaction/lib/python3.7/multiprocessing/queues.py", line 113, in get
    return _ForkingPickler.loads(res)
  File "/home/tysk-zzb01/.conda/envs/alphaction/lib/python3.7/site-packages/torch/multiprocessing/reductions.py", line 282, in rebuild_storage_fd
Traceback (most recent call last):
  File "/home/tysk-zzb01/.conda/envs/alphaction/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/tysk-zzb01/.conda/envs/alphaction/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/tysk-zzb01/AlphAction/demo/action_predictor.py", line 463, in _compute_prediction
    self.ava_predictor.clear_feature(feature_index)
  File "/home/tysk-zzb01/AlphAction/demo/action_predictor.py", line 192, in clear_feature
    del self.object_pool["SingleVideo", t]
  File "/home/tysk-zzb01/AlphAction/alphaction/structures/memory_pool.py", line 28, in __delitem__
    del self.cache[item[0]][item[1]]
KeyError: 369
    fd = df.detach()
  File "/home/tysk-zzb01/.conda/envs/alphaction/lib/python3.7/multiprocessing/resource_sharer.py", line 57, in detach
    with _resource_sharer.get_connection(self._id) as conn:
  File "/home/tysk-zzb01/.conda/envs/alphaction/lib/python3.7/multiprocessing/resource_sharer.py", line 87, in get_connection
    c = Client(address, authkey=process.current_process().authkey)
  File "/home/tysk-zzb01/.conda/envs/alphaction/lib/python3.7/multiprocessing/connection.py", line 492, in Client
    c = SocketClient(address)
  File "/home/tysk-zzb01/.conda/envs/alphaction/lib/python3.7/multiprocessing/connection.py", line 620, in SocketClient
    s.connect(address)
FileNotFoundError: [Errno 2] No such file or directory

**Comment by Seiano** [comment] 2020-11-20 03:20
### This is my change code:
    mem_timestamps_items = self.mem_pool["SingleVideo"]
    for t in self.mem_timestamps[:mem_to_release]:
        if t in mem_timestamps_items.keys():
            del self.mem_pool["SingleVideo", t]
### That's the Error and I found a question that my video time is 5:12 but the Tracker Progress frame's time is 06:32, why?
Tracker Progress: 2321 frame [06:32, 6.00 frame/s]Process Process-4:
Tracker Progress: 2321 frame [06:32, 5.91 frame/s]
Traceback (most recent call last):
File "demo.py", line 194, in
main()
File "demo.py", line 165, in main
result = ava_predictor_worker.read()
File "/home/tysk-zzb01/AlphAction/demo/action_predictor.py", line 336, in read
return self.output_queue.get_nowait()
File "/home/tysk-zzb01/.conda/envs/alphaction/lib/python3.7/multiprocessing/queues.py", line 126, in get_nowait
return self.get(False)
File "/home/tysk-zzb01/.conda/envs/alphaction/lib/python3.7/multiprocessing/queues.py", line 113, in get
return _ForkingPickler.loads(res)
File "/home/tysk-zzb01/.conda/envs/alphaction/lib/python3.7/site-packages/torch/multiprocessing/reductions.py", line 282, in rebuild_storage_fd
Traceback (most recent call last):
File "/home/tysk-zzb01/.conda/envs/alphaction/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
self.run()
File "/home/tysk-zzb01/.conda/envs/alphaction/lib/python3.7/multiprocessing/process.py", line 99, in run
self._target(*self._args, **self._kwargs)
File "/home/tysk-zzb01/AlphAction/demo/action_predictor.py", line 463, in _compute_prediction
self.ava_predictor.clear_feature(feature_index)
File "/home/tysk-zzb01/AlphAction/demo/action_predictor.py", line 192, in clear_feature
del self.object_pool["SingleVideo", t]
File "/home/tysk-zzb01/AlphAction/alphaction/structures/memory_pool.py", line 28, in delitem
del self.cache[item[0]][item[1]]
KeyError: 369
fd = df.detach()
File "/home/tysk-zzb01/.conda/envs/alphaction/lib/python3.7/multiprocessing/resource_sharer.py", line 57, in detach
with _resource_sharer.get_connection(self._id) as conn:
File "/home/tysk-zzb01/.conda/envs/alphaction/lib/python3.7/multiprocessing/resource_sharer.py", line 87, in get_connection
c = Client(address, authkey=process.current_process().authkey)
File "/home/tysk-zzb01/.conda/envs/alphaction/lib/python3.7/multiprocessing/connection.py", line 492, in Client
c = SocketClient(address)
File "/home/tysk-zzb01/.conda/envs/alphaction/lib/python3.7/multiprocessing/connection.py", line 620, in SocketClient
s.connect(address)
FileNotFoundError: [Errno 2] No such file or directory

@pxssw

**Comment by Seiano** [comment] 2020-11-20 07:00
> > Mybe my video is too long? my video time is 5 minutes .
> > How long can this method handle video?
> 
> Sorry, I don't understand your reply. What problem did you encounter? @z1z9b89

The problem I encountered was that I wanted to deal with a 6-minute video test, but I couldn't save it all. I only saved it to 2 minutes, and then the program stopped.  @yelantf

**Comment by yelantf** [comment] 2020-11-20 07:38
I am really confused now. Is not this happening when run in the webcam mode? Then why your video have a pre-defined length? And @Seiano and @z1z9b89 are both your accounts? Please describe the problem clearly and keep this issue clean and easy to understand, thanks!

**Comment by Seiano** [comment] 2020-11-20 08:07
Sorry, I don't want to use two accounts to solve this problem. Because www.gitlab.com needs to be associated with an account, I will log in with this account. I'm sorry for the trouble caused to you!
This computer doesn't have  a camera. Another computer with a camera  is broken.

**Comment by yelantf** [comment] 2020-11-20 08:53
Understood. After inspecting your log in the e-mail, I modified the code a little bit and pushed it to a new branch [`issue-36`](https://github.com/MVIG-SJTU/AlphAction/tree/issue-36). Could you switch to this branch and try it out to see if it solved your problem?

**Comment by pxssw** [comment] 2020-11-20 11:10
> self.ava_predictor.clear_feature(feature_index)
> File "/home/tysk-zzb01/AlphAction/demo/action_predictor.py", line 192, in clear_feature
> del self.object_pool["SingleVideo", t]
> File "/home/tysk-zzb01/AlphAction/alphaction/structures/memory_pool.py", line 28, in delitem
> del self.cache[item[0]][item[1]]

According to the log info,  the "clear_feature" of your work still has some little bug. Can the author's change of above solve it?  Or can you send me the video you test?(If you are free, my address is gramaps@163.com)

**Comment by pxssw** [comment] 2020-11-20 11:12
> ### This is my change code:
> ```
> mem_timestamps_items = self.mem_pool["SingleVideo"]
> for t in self.mem_timestamps[:mem_to_release]:
>     if t in mem_timestamps_items.keys():
>         del self.mem_pool["SingleVideo", t]
> ```
> 
> ### That's the Error and I found a question that my video time is 5:12 but the Tracker Progress frame's time is 06:32, why?
> Tracker Progress: 2321 frame [06:32, 6.00 frame/s]Process Process-4:
> Tracker Progress: 2321 frame [06:32, 5.91 frame/s]
> Traceback (most recent call last):
> File "demo.py", line 194, in
> main()
> File "demo.py", line 165, in main
> result = ava_predictor_worker.read()
> File "/home/tysk-zzb01/AlphAction/demo/action_predictor.py", line 336, in read
> return self.output_queue.get_nowait()
> File "/home/tysk-zzb01/.conda/envs/alphaction/lib/python3.7/multiprocessing/queues.py", line 126, in get_nowait
> return self.get(False)
> File "/home/tysk-zzb01/.conda/envs/alphaction/lib/python3.7/multiprocessing/queues.py", line 113, in get
> return _ForkingPickler.loads(res)
> File "/home/tysk-zzb01/.conda/envs/alphaction/lib/python3.7/site-packages/torch/multiprocessing/reductions.py", line 282, in rebuild_storage_fd
> Traceback (most recent call last):
> File "/home/tysk-zzb01/.conda/envs/alphaction/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
> self.run()
> File "/home/tysk-zzb01/.conda/envs/alphaction/lib/python3.7/multiprocessing/process.py", line 99, in run
> self._target(*self._args, **self._kwargs)
> File "/home/tysk-zzb01/AlphAction/demo/action_predictor.py", line 463, in _compute_prediction
> self.ava_predictor.clear_feature(feature_index)
> File "/home/tysk-zzb01/AlphAction/demo/action_predictor.py", line 192, in clear_feature
> del self.object_pool["SingleVideo", t]
> File "/home/tysk-zzb01/AlphAction/alphaction/structures/memory_pool.py", line 28, in delitem
> del self.cache[item[0]][item[1]]
> KeyError: 369
> fd = df.detach()
> File "/home/tysk-zzb01/.conda/envs/alphaction/lib/python3.7/multiprocessing/resource_sharer.py", line 57, in detach
> with _resource_sharer.get_connection(self._id) as conn:
> File "/home/tysk-zzb01/.conda/envs/alphaction/lib/python3.7/multiprocessing/resource_sharer.py", line 87, in get_connection
> c = Client(address, authkey=process.current_process().authkey)
> File "/home/tysk-zzb01/.conda/envs/alphaction/lib/python3.7/multiprocessing/connection.py", line 492, in Client
> c = SocketClient(address)
> File "/home/tysk-zzb01/.conda/envs/alphaction/lib/python3.7/multiprocessing/connection.py", line 620, in SocketClient
> s.connect(address)
> FileNotFoundError: [Errno 2] No such file or directory
> 
> @pxssw

According to the log info, the "clear_feature" of your work still has some little problems. Can the author's change of above solve it? Or can you send me the video you test?(If you are free, my address is gramaps@163.com) @Seiano

**Comment by Seiano** [comment] 2020-11-23 01:25
When I redeployment  the file  action_predictor.py  form your [https://github.com/MVIG-SJTU/AlphAction/tree/issue-36](url)  the Error disappeared. 3 Q for your help!
 I found persion detector  not so accurate！I while send you my  video.

**Comment by yelantf** [comment] 2020-11-23 08:55
@Seiano Is the performance of person detector about the change in the new branch? Or is it a common problem no matter this change is applied or not?

**Comment by yelantf** [comment] 2020-11-23 11:14
@Seiano Your video has been received. Here are some information that I think could help. 

1. You may need to adjust some hyper-parameters in detector/tracker_cfg.py for better detection effects.
2. Although the tracker use yolo as its detection model, it is not as easy as simply detecting human. And since the tracker is trained on some pedestrian tracking dataset, where humans are often just walking and showing their full body parts, the effects of the tracker will not as perfect as you want when applied to other scenes(e.g., different pose, only part of body).

**Comment by yelantf** [comment] 2020-11-23 11:14
Anyway, now that the original problem of this issue has already been fixed, I am closing this issue now.

**Closed as completed by yelantf** 2020-11-23 11:14 UTC
Labels: bug, fixed
